version: '3'
services:
  # DATABASE
  rethinkdb:
    image: 'rethinkdb:latest'
    volumes: # persist data
     - ./docker/rethinkdb/data:/data
  
  # fancy REST -> Realtime API middleware
  pushpin:
    image: fanout/pushpin
    volumes: 
      - ./docker/pushpin/routes:/etc/pushpin/routes
    logging:
      driver: "none"
  
  # REST API with pushpin integration
  api:
    image: help/api/prod
    build: 
      context: ./backend 
      dockerfile: ./prod.Dockerfile
    depends_on:
      - rethinkdb
    
  caddy2:
    image: "caddy:2.4.5-alpine"
    volumes:
      - ./frontend/dist/help:/srv/
      - ./docker/caddy/Caddyfile.prod:/etc/caddy/Caddyfile
      - ./docker/caddy/data:/data
    ports:
      - "80:80"
      - "443:443"

